#!/usr/bin/env python3
"""format-output.py — Convert final summary to the requested output format.

Usage:
  python3 format-output.py <input-file> <format> <output-path>

Formats:
  text     — Plain .txt file (passthrough)
  markdown — .md file with Markdown header
  email    — .html file styled for email clients
"""
import sys
import os
import html as html_lib
import re

def to_text(content: str) -> str:
    return content

def to_markdown(content: str) -> str:
    # If already has markdown heading, return as-is
    if content.lstrip().startswith("#"):
        return content
    return f"# Lenx Task Data Summary\n\n{content}"

def to_email_html(content: str) -> str:
    """Convert plain/markdown text to inline-styled HTML for email."""
    lines = content.split("\n")
    body_parts = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            body_parts.append("<br>")
            continue

        # Headings
        if stripped.startswith("### "):
            text = html_lib.escape(stripped[4:])
            body_parts.append(
                f'<h3 style="font-size:16px;color:#333;margin:16px 0 8px 0;'
                f'font-family:Arial,sans-serif;">{text}</h3>'
            )
        elif stripped.startswith("## "):
            text = html_lib.escape(stripped[3:])
            body_parts.append(
                f'<h2 style="font-size:18px;color:#222;margin:20px 0 10px 0;'
                f'font-family:Arial,sans-serif;">{text}</h2>'
            )
        elif stripped.startswith("# "):
            text = html_lib.escape(stripped[2:])
            body_parts.append(
                f'<h1 style="font-size:22px;color:#111;margin:24px 0 12px 0;'
                f'font-family:Arial,sans-serif;">{text}</h1>'
            )
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = html_lib.escape(stripped[2:])
            # Bold markers
            text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
            body_parts.append(
                f'<li style="margin:4px 0;font-family:Arial,sans-serif;'
                f'font-size:14px;color:#444;">{text}</li>'
            )
        else:
            text = html_lib.escape(stripped)
            text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
            body_parts.append(
                f'<p style="margin:6px 0;font-family:Arial,sans-serif;'
                f'font-size:14px;color:#444;line-height:1.6;">{text}</p>'
            )

    body = "\n".join(body_parts)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lenx Task Data Summary</title>
</head>
<body style="margin:0;padding:0;background:#f5f5f5;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;">
<tr><td align="center" style="padding:20px 10px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0"
       style="background:#ffffff;border-radius:8px;overflow:hidden;
              box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<tr><td style="background:#1a1a2e;padding:24px 32px;">
  <h1 style="margin:0;font-family:Arial,sans-serif;font-size:20px;color:#ffffff;">
    Lenx Task Data Summary
  </h1>
</td></tr>
<tr><td style="padding:24px 32px;">
{body}
</td></tr>
<tr><td style="padding:16px 32px;background:#fafafa;border-top:1px solid #eee;">
  <p style="margin:0;font-family:Arial,sans-serif;font-size:12px;color:#999;">
    Generated by lenx-task-summariser
  </p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""

def main():
    input_file = sys.argv[1]
    fmt = sys.argv[2].lower()
    output_path = sys.argv[3]

    with open(input_file, "r", encoding="utf-8") as f:
        content = f.read()

    if fmt == "text":
        result = to_text(content)
    elif fmt == "markdown":
        result = to_markdown(content)
    elif fmt == "email":
        result = to_email_html(content)
    else:
        print(f"Unknown format: {fmt}", file=sys.stderr)
        sys.exit(1)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(result)

    print(output_path)

if __name__ == "__main__":
    main()

